### ISSUE TITLE
Layer to KML (with image attachments) Error

### ISSUE THREAD

**Issue by katbri** [arcpy/sample-gp-tools#15]
Hello,
I would like to convert to KMZ with attachments so that colleagues can view the location of photos in Google Earth. I found this Layer to KML tool to use: https://www.arcgis.com/home/item.html?id=5d8704c938ea4715b59eebabcd96c1d9

I am using ArcGIS 10.7 I downloaded my data from ArcGIS Online as a FGDB. Each point location has at least 1 photo, some points 3-4 photos. When I run the tool, I get the below error, any advice you could provide would be most appreciated. I have run the "Make Feature Layer" tool to ensure it is in Feature Layer format and I viewed my ObjectID values, verified the points were non-sequential and ensured that the Allow Unique ID field was checked on. Thanks!

Failed script Layer2KMLAttach...

Traceback (most recent call last):
  File "C:\Users\Katie\Downloads\Toolbox\Layer_to_KML_attachment.py", line 177, in <module>
    arcpy.AddField_management(inputFeatures, "tempIDField", "TEXT")
  File "c:\program files (x86)\arcgis\desktop10.7\arcpy\arcpy\management.py", line 3429, in AddField
    raise e
ExecuteError: ERROR 999999: Error executing function.
The application is not licensed to create or modify schema for this type of data 
Failed to execute (AddField).

Failed to execute (Layer2KMLAttach).

**Comment by engzean** [comment]
hello 
when i execute the tools the message appears  
Running script Layer2KMLAttach...
Could not find an attachment table. Ensure the attachment table is properly
referenced through a relationship class in the same workspace as the input features.
Completed script Layer2KMLAttach...
Failed to execute (Layer2KMLAttach).
Failed at Mon Oct 17 15:22:20 2022 (Elapsed Time: 0.05 seconds
